# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-16 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('published', models.BooleanField(default=True)),
                ('recipe', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='recipes.Recipe')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
