# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('units', models.CharField(choices=[('tbsp', 'tablespoon'), ('tsp', 'teaspoon'), ('c', 'cup'), ('qt', 'quart')], max_length=5)),
                ('preparation', models.CharField(max_length=100, null=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Ingredient')),
            ],
            options={
                'verbose_name_plural': 'ingredient quantities',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name needed', max_length=100)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveSmallIntegerField(default=1)),
                ('description', models.TextField(null=True)),
                ('ingredient_quantities', models.ManyToManyField(to='recipes.IngredientQuantity')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_steps',
            field=models.ManyToManyField(to='recipes.RecipeStep'),
        ),
    ]
