# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-16 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(default=0)),
                ('physical_quantity', models.CharField(choices=[(0, 'length'), (1, 'area'), (2, 'volume'), (3, 'mass'), (4, 'count'), (5, 'miscellaneous')], max_length=1)),
                ('measure', models.FloatField()),
                ('unit_name', models.CharField(blank=True, max_length=100, null=True)),
                ('preparation', models.CharField(blank=True, max_length=100, null=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipes.Ingredient')),
            ],
            options={
                'default_related_name': 'ingredient_quantity_set',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prep_time', models.DurationField()),
                ('cooking_time', models.DurationField()),
                ('total_time', models.DurationField()),
                ('title', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
                ('serves', models.PositiveSmallIntegerField()),
                ('source', models.CharField(max_length=1000)),
                ('miscellaneous_info', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(default=0)),
                ('instruction', models.CharField(max_length=1000)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe')),
            ],
            options={
                'default_related_name': 'recipe_step_set',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, choices=[(0, 'cooking methods'), (1, 'courses'), (2, 'dietary'), (3, 'key ingredients'), (4, 'seasons'), (5, 'cuisine'), (6, 'dessert types'), (7, 'occasion')], max_length=1, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(to='recipes.Tag'),
        ),
        migrations.AddField(
            model_name='ingredientquantity',
            name='recipe_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.RecipeStep'),
        ),
    ]
