# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cooking_method',
            field=models.CharField(choices=[('BAKE', 'bake'), ('BLENDER', 'blender'), ('JUICE', 'juice'), ('RAW', 'raw'), ('SLOW', 'slow-cooker'), ('FRY', 'fry'), ('ROAST', 'roast'), ('GRILL', 'grill'), ('SAUTE', 'saute')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='course',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='dietary',
            field=models.CharField(choices=[('VEGAN', 'vegan'), ('VEGE', 'vegetarian'), ('LOW', 'low-carb'), ('NONUTS', 'nut-free'), ('NOSOY', 'soy-free'), ('NOGLUTEN', 'gluten-free')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ingredientquantity',
            name='units',
            field=models.CharField(choices=[('TBSP', 'tablespoon'), ('TSP', 'teaspoon'), ('CUP', 'cup'), ('QUART', 'quart')], max_length=10),
        ),
    ]
