# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20160409_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_method',
            field=models.CharField(choices=[(1, 'bake'), (2, 'blender'), (3, 'juice'), (4, 'raw'), (5, 'slow-cooker'), (6, 'fry'), (7, 'roast'), (8, 'grill'), (9, 'saute')], max_length=1, null=True),
        ),
    ]
