# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20160409_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientquantity',
            name='preparation',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='course',
        ),
        migrations.AlterField(
            model_name='ingredientquantity',
            name='units',
            field=models.CharField(choices=[(1, 'tablespoon'), (2, 'teaspoon'), (3, 'cup'), (4, 'quart')], max_length=10),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='dietary',
            field=models.CharField(choices=[(1, 'vegan'), (2, 'vegetarian'), (3, 'low-carb'), (4, 'nut-free'), (5, 'soy-free'), (6, 'gluten-free')], max_length=10, null=True),
        ),
    ]
