# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20160409_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='dietary',
        ),
        migrations.AddField(
            model_name='recipe',
            name='diet',
            field=models.CharField(choices=[(1, 'vegan'), (2, 'vegetarian'), (3, 'low-carb'), (4, 'nut-free'), (5, 'soy-free'), (6, 'gluten-free')], max_length=1, null=True),
        ),
    ]
